language: en

reviews:
  profile: "chill"

request_changes_workflow: true

auto_review:
  enabled: true
  drafts: false

security_scanning:
  enabled: true
  scan_dependencies: true
  scan_secrets: true
  vulnerability_alerts: true
  sast_enabled: true

ai_suggestions:
  enabled: true
  features:
    - code_optimization
    - security_best_practices
    - performance_improvements
    - accessibility_enhancements
    - test_coverage

    - path: "app/**/*.tsx"
      instructions: |
        - Optimize component structure and hooks
        - Address accessibility and theme support
        - Secure event handlers and prop validation

    - path: "app/lib/actions/*.ts"
      instructions: |
        - Validate inputs and handle errors
        - Check auth, rate limiting, and DB optimization

    - path: "lib/supabase/*.ts"
      instructions: |
        - Review DB queries, auth, and data encryption
        - Monitor for sensitive data leaks

    - path: "app/(auth)/**/*.tsx"
      instructions: |
        - Enforce HTTPS, secure sessions, and rate limits
        - Review cookie handling and JWT usage

severity:
  critical:
    - security_vulnerabilities
    - memory_leaks
    - authentication_bypass
    - data_exposure
  high:
    - performance_issues
    - security_misconfiguration
    - insecure_dependencies
  medium:
    - code_style_violations
    - accessibility_issues
    - type_safety_concerns
  low:
    - documentation_missing
    - code_duplication
    - naming_conventions

code_metrics:
  enabled: true
  analyze:
    - cyclomatic_complexity
    - cognitive_complexity
    - maintainability_index
    - code_duplication
    - test_coverage
